# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            αλάνα
tagline:          ''
description:      'σκέψεις κείμενα ιδέες και διάφορες προσωπικές απόψεις, ένας
μικρός χώρος που αλωνίζω'
url:              http://chief.github.io
baseurl:          /
excerpt_separator: "<!--more-->"

author:
  name:           'Giorgos Tsiftsis'
  url:            https://twitter.com/giorgostsiftsis


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/chief/chief.github.io

gems: [redcarpet, jekyll-paginate]
